variables:
  BINARY_NAME: $CI_PROJECT_NAME
  
stages:
  - sonar
  - docker
  
### Sonarqube check ###
sonarqube-check:
  # when: manual
  image: $PRIVATE_REGISTRY/sonar-scanner-cli:latest
  stage: sonar
  script:
    - sonar-scanner

docker_dev_rct:
  stage: docker
  only:
    - /^develop$/
    - /^release\/.*$/
  cache: {}
  script:
    - docker build --pull --no-cache -f Dockerfile.prod -t $PRV_REGISTRY/$BINARY_NAME:build-${CI_COMMIT_SHA:0:8} .
    - docker push $PRV_REGISTRY/$BINARY_NAME:build-${CI_COMMIT_SHA:0:8}
    - mkdir image
    - cd image
    - docker save $PRV_REGISTRY/$BINARY_NAME:build-${CI_COMMIT_SHA:0:8} > $BINARY_NAME:build-${CI_COMMIT_SHA:0:8}.tar
  artifacts:
    paths:
      - image/
    expire_in: '3600' #1 hour

    
docker_prod:
  stage: docker
  only:
    - tags
  cache: {}
  script:
    - docker build --pull --no-cache -f Dockerfile.prod -t $PRV_REGISTRY/$BINARY_NAME:${CI_COMMIT_REF_NAME} .
    - docker push $PRV_REGISTRY/$BINARY_NAME:${CI_COMMIT_REF_NAME}


